### ISSUE TITLE
[Cần giúp đỡ] Font size từ điển quá nhỏ cho máy đọc sách Kobo Clara

### ISSUE THREAD

**Issue by meomap13** [lelinhtinh/kobo-tieng-viet#1]
Chào bạn,
Mình có download 2 từ điển Anh Việt và Viêt Anh từ nguồn của bạn và chép vào máy đọc sách như hướng dẫn. Tuy nhiên font chữ trên từ điển ở máy đọc sách Kobo Clara quá nhỏ để đọc (chỉ khoảng 1/3 của từ điển mặc định của Kobo). Nếu không phiền nhờ bạn điều chỉnh giúp mình để độ lớn font của từ điển tăng lên khoảng 3 lần so với độ lớn hiện tại được không ạ? Mình cảm ơn bạn rất nhiều. Đây là email của mình: freewill.mail@gmail.com
![123296618_10158030081442872_8229478901448479042_n](https://user-images.githubusercontent.com/74047262/98350668-3b569500-204e-11eb-88d1-4d9b5aa02120.jpg)

**Comment by lelinhtinh** [comment]
Do bản update gần đây của Kobo làm nhỏ font size từ điển đấy. 
Cách nhanh nhất là downgrade về phiên bản **4.23.15548**.
Download [tại đây](http://download.kobobooks.com/firmwares/kobo7/Aug2020/kobo-update-4.23.15548.zip) hoặc [link dự phòng](https://kbdownload1-a.akamaihd.net/firmwares/kobo7/Aug2020/kobo-update-4.23.15548.zip).

Còn cách khác hơi phức tạp chút, đó là dùng kobopatch để [sửa font-size của từ điển](https://github.com/pgaskin/kobopatch-patches/blob/601e72854fcb3a23997c5c5eaffd48abe63b29e1/src/versions/4.24.15676/libnickel.so.1.0.0.yaml/jackie_w.yaml#L82).
Hoặc... không làm gì cả, chờ bản update sau của Kobo.

**Comment by meomap13** [comment]
Cám ơn bạn nhiều

**Comment by lelinhtinh** [comment]
@meomap13 lướt trên mobileread gặp [bài đăng của bạn](https://www.mobileread.com/forums/showthread.php?t=334602), mình đã convert hết table theo gợi ý của @jackie_w thì không bị lỗi chữ nhỏ nữa. Bạn cài thử xem sao.

[dicthtml-en-vi.zip](https://github.com/lelinhtinh/kobo-tieng-viet/files/5538576/dicthtml-en-vi.zip)
[dicthtml-vi-en.zip](https://github.com/lelinhtinh/kobo-tieng-viet/files/5538577/dicthtml-vi-en.zip)
