### ISSUE TITLE
File .tgz sửa lỗi font tiếng việt không hoạt động trên patch 4.38

### ISSUE THREAD

**Issue by nnfjuu** [lelinhtinh/kobo-tieng-viet#2]
Hi b! Mình quên tắt wifi nên máy tự cập nhật lên bản mới nhất 4.38 (hôm 22/08/2023). Sau đó mình copy file .tgz để sửa lỗi font hệ thống thì ko được nữa. Nhờ bạn fix giúp. Cảm ơn b nhiều!

**Comment by nnfjuu** [comment]
Mình có font Avenir Next và Georgia được [việt hóa](https://hellabyte.one/drive/s/64f02ce1a3fb848ac103cecd) nên gửi b nếu cần làm patch mới.

**Comment by lelinhtinh** [comment]
Mình dùng Kobo Clara 2E, hiện tại nó vẫn còn ở v4.37 nên chưa kiểm tra lỗi này được.
Bạn có thể tạm thời [downgrade](https://github.com/lelinhtinh/kobo-tieng-viet/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-h%E1%BA%A1-c%E1%BA%A5p-Kobo-v%E1%BB%81-phi%C3%AAn-b%E1%BA%A3n-c%C5%A9-h%C6%A1n) về phiên bản cũ, hoặc thử trình đọc khác như [KOReader & Plato](https://www.mobileread.com/forums/showthread.php?t=314220).

**Comment by nnfjuu** [comment]
Mình dùng clara hd mà sao nó cập nhật sớm thế nhỉ 😅. Ok thank b nha!

**Comment by lelinhtinh** [comment]
Phiên bản 4.38 bị tạm ngưng phát hành rồi, các bản update giờ chỉ đến 4.37

**Comment by nnfjuu** [comment]
Ồ, b nói mình mới mò lên mobileread đọc. Vậy chờ hãng nó fix r mình dùng lại file xem sao.

**Comment by nnfjuu** [comment]
Mình thử lại patch font ok rồi nhé. :D vẫn chạy tốt cho bản 4.38
