### ISSUE TITLE
Update cho Kobo Colour mới

### ISSUE THREAD

**Issue by quanganhdo** [lelinhtinh/kobo-tieng-viet#3]
Firmware mới cho Kobo Colour không ship kèm Avenir Next và Georgia nên mấy font chỉnh sửa này không còn tác dụng. Bạn có tips nào để xác định font cần overwrite cho firmware mới này không?

Cảm ơn nhiều.

**Comment by lelinhtinh** [comment]
Bạn tải firmware về, giải nén tệp **KoboRoot.tgz** sau đó dò theo đường dẫn:

    /usr/local/Trolltech/QtEmbedded-4.6.2-arm/lib/fonts/

**Comment by lelinhtinh** [comment]
Trông có vẻ như 2 font mới là `Rakuten Serif` và `Rakuten Sans`.

**Comment by quanganhdo** [comment]
Mình diff 2 fonts folder của firmware cũ và mới thì thấy 2 font Rakuten Serif và Sans không đổi; chỉ khác là Kobo add và remove các font cũ (bao gồm Avenir Next và Georgia). Mấy font built-in thì encrypted/obfuscated nên không edit được; vậy chắc phải modify font fallback?
 
<img width="1582" alt="Screenshot 2024-05-03 at 9 52 46 AM" src="https://github.com/lelinhtinh/kobo-tieng-viet/assets/18567/4eef862f-f1f3-40c5-a5e8-f49b89f78633">

<img width="1582" alt="Screenshot 2024-05-03 at 9 52 48 AM" src="https://github.com/lelinhtinh/kobo-tieng-viet/assets/18567/b1592b94-aee3-460e-88e7-9223cc49f349">

**Comment by lelinhtinh** [comment]
Mình xem bên [kobopatch-patches](https://github.com/pgaskin/kobopatch-patches/blob/master/src%2Fversions%2F4.39.22801%2Flibrmsdk.so.1.0.0.yaml%2Fgeoffr.yaml) chứ không có máy test.
Bạn thử thay thế từng font xem sao.

**Comment by lelinhtinh** [comment]
[KoboRootTest2.zip](https://github.com/lelinhtinh/kobo-tieng-viet/files/15208573/KoboRootTest2.zip)

**Comment by quanganhdo** [comment]
Không được bạn ạ, vẫn ô vuông ở home + mục lục + từ điển.

**Comment by quanganhdo** [comment]
À, file trên không work, nhưng file trong release 0.5.0 thì ngon bạn nhé 👍 Cảm ơn rất rất nhiều!

**Comment by lelinhtinh** [comment]
Không có máy khó test, file đó dùng được cho Kobo Clara BW, không biết Libra Color nó sài font chi.

**Comment by quanganhdo** [comment]
Mình update comment bên trên, file trong release có dùng được bạn nhé. FYI mình có vừa gửi email theo profile GH của bạn.

**Comment by simzen85** [comment]
@quanganhdo mình dùng patch 0.5.0 thì tiếng Việt hiển thị ở menu ổn, tuy nhiên ở chế độ sleeping, khi máy hiện các chương của truyện thì thấy vẫn lỗi, bạn có gặp tình trạng này không ? Tks

**Comment by quanganhdo** [comment]
@simzen85 Mình không thấy lỗi tiếng Việt nào trên màn hình chính / từ điển / trình đọc sách / mục lục. Không hiểu bạn đang nói tới khu vực nào nhỉ? Sách nào bạn cũng bị hay gì?

**Comment by quanganhdo** [comment]
@lelinhtinh Đúng là một số chỗ còn bị lỗi font bạn ạ - book title ngoài danh sách, mục lục. Đây mình dùng patch 0.5.0 trên firmware mới nhất là 4.40.23081. Hình như chỉ dính chữ "ỉ"

![screen_001](https://github.com/user-attachments/assets/34568c90-750a-4715-943e-717051585d50)
![screen_002](https://github.com/user-attachments/assets/64ce6d24-c8f8-47bb-80e5-fcbc526203f1)

**Comment by Slotheacientone** [comment]
@lelinhtinh 
Em cũng thấy là hình như chỉ có chữ "ỉ" là bị lỗi font trên kobo clara bw ạ

**Comment by lelinhtinh** [comment]
Sửa lỗi chữ `ỉ`: https://github.com/lelinhtinh/kobo-tieng-viet/releases/tag/v1.0.0
